services:
  jupyter-notebook:
    image:  ntruesdell/dsci522-dockerfile-milestone:latest
    ports:
      - "8888:8888"
    volumes:
     - ./:/workplace
    working_dir: /workplace
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64