name: dsci573
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py312h927b8db_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alabaster=0.7.16=pyhd8ed1ab_0
  - altair=5.4.1=pyhd8ed1ab_3
  - altair-all=5.4.1=pyhd8ed1ab_3
  - altair_tiles=0.4.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - anywidget=0.9.21=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312he06e257_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_3
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h06c2b12_7
  - aws-c-cal=0.9.10=ha82e055_1
  - aws-c-common=0.12.5=hfd05255_1
  - aws-c-compression=0.3.1=h83e01e5_8
  - aws-c-event-stream=0.5.6=h3116ff1_6
  - aws-c-http=0.10.7=h52d8906_4
  - aws-c-io=0.23.3=h6f46d10_3
  - aws-c-mqtt=0.13.3=h9821516_10
  - aws-c-s3=0.10.1=he380ad5_2
  - aws-c-sdkutils=0.2.4=h83e01e5_3
  - aws-checksums=0.2.7=h83e01e5_4
  - aws-crt-cpp=0.35.2=h1a9a3a2_4
  - aws-sdk-cpp=1.11.606=h6446450_7
  - babel=2.17.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhd8ed1ab_1
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blinker=1.9.0=pyhff2d567_0
  - boltons=25.0.0=pyhd8ed1ab_0
  - bottleneck=1.6.0=np2py312h226b611_3
  - brotli=1.2.0=h17ff524_0
  - brotli-bin=1.2.0=h6910e44_0
  - brotli-python=1.2.0=py312h9d5906e_0
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.11.12=h4c7d964_0
  - cachecontrol=0.14.3=pyha770c72_0
  - cachecontrol-with-filecache=0.14.3=pyhd8ed1ab_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.2.2=pyhd8ed1ab_0
  - cairo=1.18.4=h5782bbf_0
  - catalogue=2.0.10=py312h2e8e312_2
  - catboost=1.2.7=py312h5eb20be_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py312he06e257_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh7428d3b_0
  - click-default-group=1.2.4=pyhd8ed1ab_1
  - cloudpathlib=0.23.0=pyhd8ed1ab_0
  - cloudpickle=3.1.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - conda-lock=3.0.4=pyha6a9232_1
  - conda-package-streaming=0.12.0=pyhd8ed1ab_0
  - confection=0.1.5=pyhecae5ae_0
  - confuse=2.1.0=pyhd8ed1ab_0
  - contourpy=1.3.3=py312hf90b1b7_3
  - cpython=3.12.12=py312hd8ed1ab_1
  - crashtest=0.4.1=pyhd8ed1ab_1
  - cryptography=46.0.3=py312h84d000f_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cymem=2.0.13=py312hbb81ca0_0
  - cython-blis=1.3.3=py312h196c9fc_0
  - debugpy=1.8.17=py312ha1a9051_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhd8ed1ab_0
  - distlib=0.4.0=pyhd8ed1ab_0
  - docutils=0.22.3=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - dulwich=0.22.8=py312h2615798_0
  - eli5=0.16.0=pyh29332c3_0
  - ensureconda=1.6.0=pyhcf101f3_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fica=0.4.1=pyhd8ed1ab_1
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py312h05f76fc_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - frozenlist=1.7.0=py312hfdf67e6_0
  - getopt-win32=0.1=h6a83c73_3
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - google-api-core=2.28.1=pyhd8ed1ab_0
  - google-api-python-client=2.187.0=pyh332efcf_0
  - google-auth=2.41.1=pyhd8ed1ab_0
  - google-auth-httplib2=0.2.1=pyhd8ed1ab_0
  - google-auth-oauthlib=1.2.3=pyhd8ed1ab_1
  - googleapis-common-protos=1.72.0=pyhd8ed1ab_0
  - graphite2=1.3.14=hac47afa_2
  - graphviz=14.0.4=ha5e8f4b_0
  - gts=0.7.6=h6b5321d_4
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=h5f2951f_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - htmlmin=0.1.12=pyhca7485f_2
  - httpcore=1.0.9=pyh29332c3_0
  - httplib2=0.31.0=pyhd8ed1ab_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - imagehash=4.3.2=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - imbalanced-learn=0.14.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipylab=1.1.0=pyhe01879c_0
  - ipython=9.7.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jaraco.classes=3.4.0=pyhd8ed1ab_2
  - jaraco.context=6.0.1=pyhd8ed1ab_0
  - jaraco.functools=4.3.0=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py312h2e8e312_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.10=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - jupytext=1.18.1=pyh80e38bb_0
  - keyring=25.7.0=pyh7428d3b_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.9=py312h78d62e6_2
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libarrow=22.0.0=h117da51_4_cpu
  - libarrow-acero=22.0.0=h7d8d6a5_4_cpu
  - libarrow-compute=22.0.0=h2db994a_4_cpu
  - libarrow-dataset=22.0.0=h7d8d6a5_4_cpu
  - libarrow-substrait=22.0.0=hf865cc0_4_cpu
  - libblas=3.11.0=1_hf2e6a31_mkl
  - libboost=1.88.0=h9dfe17d_6
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libcblas=3.11.0=1_h2a3cdd5_mkl
  - libclang13=21.1.5=default_ha2db4b5_0
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.17.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libgd=2.3.3=h7208af6_11
  - libglib=2.86.1=hd9c3897_2
  - libgomp=15.2.0=h1383e82_7
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=1_hf9ab0e9_mkl
  - liblightgbm=4.6.0=cpu_h5d2ca61_6
  - liblzma=5.8.1=h2466b09_2
  - libparquet=22.0.0=h7051d1f_4_cpu
  - libpng=1.6.50=h7351971_1
  - libprotobuf=6.31.1=hdcda5b4_2
  - libre2-11=2025.11.05=h0eb2380_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.0=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.1=h8f73337_1
  - libutf8proc=2.11.1=hb980946_0
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxgboost=3.1.1=cpu_hd161407_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - lightgbm=4.6.0=cpu_py_6
  - llvm-openmp=21.1.5=h4fa8253_2
  - llvmlite=0.45.1=py312hdb9728c_0
  - lz4-c=1.10.0=h2466b09_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py312h05f76fc_0
  - matplotlib=3.10.8=py312h2e8e312_0
  - matplotlib-base=3.10.8=py312h0ebf65c_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdit-py-plugins=0.5.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mercantile=1.2.1=pyhd8ed1ab_1
  - missingno=0.5.2=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2025.3.0=hac47afa_454
  - more-itertools=10.8.0=pyhd8ed1ab_0
  - msgpack-python=1.1.2=py312hf90b1b7_1
  - multidict=6.6.3=py312h05f76fc_0
  - multimethod=1.4=py_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - murmurhash=1.0.14=py312ha1a9051_0
  - narwhals=2.12.0=pyhcf101f3_0
  - nb_conda_kernels=2.5.1=pyh7428d3b_2
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - nltk=3.9.2=pyhcf101f3_1
  - notebook=7.4.7=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.62.1=py312h9a042f1_0
  - numpy=1.26.4=py312h8753938_0
  - oauthlib=3.3.1=pyhd8ed1ab_0
  - opencl-headers=2025.06.13=he0c23c2_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - orc=2.2.1=h7414dfc_0
  - otter-grader=6.1.6=pyh7f80d73_2
  - otter-grader-base=6.1.6=pyhcf101f3_2
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hc128f0a_1
  - pandas-profiling=3.0.0=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.4=h03d888a_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h3402e2f_0
  - phik=0.12.5=py312h78d62e6_1
  - pillow=12.0.0=py312h036897e_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - pkginfo=1.12.1.2=pyhd8ed1ab_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotly=6.5.0=pyhd8ed1ab_0
  - preshed=3.0.12=py312hbb81ca0_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py312h31fea79_0
  - proto-plus=1.26.1=pyhd8ed1ab_0
  - protobuf=6.31.1=py312hcb3287e_2
  - psutil=7.1.3=py312he5662c2_0
  - psygnal=0.15.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.1.1=cpu_pyh35227d3_0
  - pyarrow=22.0.0=py312h2e8e312_0
  - pyarrow-core=22.0.0=py312h85419b5_0_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.4=pyh3cfb1c2_0
  - pydantic-core=2.41.5=py312hdabe01f_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproject_hooks=1.2.0=pyhd8ed1ab_1
  - pyside6=6.9.3=py312h0c8bdd4_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.12=h0159041_1_cpython
  - python-build=1.3.0=pyhff2d567_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.12=hd8ed1ab_1
  - python-graphviz=0.21=pyhbacfb6d_0
  - python-installer=0.7.0=pyhff2d567_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-on-whales=0.79.0=pyh332efcf_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pywavelets=1.9.0=py312h196c9fc_2
  - pywin32=311=py312h829343e_1
  - pywin32-ctypes=0.2.3=py312h2e8e312_3
  - pywinpty=2.0.15=py312h275cf98_1
  - pyyaml=6.0.3=py312h05f76fc_0
  - pyzmq=27.1.0=py312hbb5da91_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.3=ha0de62e_1
  - re2=2025.11.05=ha104f34_0
  - referencing=0.37.0=pyhcf101f3_0
  - regex=2025.11.3=py312he06e257_1
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - requests-toolbelt=1.0.0=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=14.2.0=pyhcf101f3_0
  - rpds-py=0.29.0=py312hdabe01f_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - ruamel.yaml=0.18.16=py312he06e257_0
  - ruamel.yaml.clib=0.2.14=py312he06e257_0
  - scikit-learn=1.7.2=py312h91ac024_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - semver=3.0.4=pyhd8ed1ab_0
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.9.0=pyhff2d567_0
  - shap=0.48.0=cpu_py312h923d338_1
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - slicer=0.0.8=pyhd8ed1ab_0
  - smart-open=7.5.0=h0f9f196_0
  - smart_open=7.5.0=pyhcf101f3_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h7fa0ca8_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - soupsieve=2.8=pyhd8ed1ab_0
  - spacy=3.8.11=py312he3e9d37_0
  - spacy-legacy=3.0.12=pyhd8ed1ab_0
  - spacy-loggers=1.0.5=pyhd8ed1ab_0
  - sphinx=3.5.3=pyhd3eb1b0_0
  - sphinxcontrib-applehelp=1.0.4=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.1=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - srsly=2.5.2=py312hbb81ca0_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py312h196c9fc_1
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tangled-up-in-unicode=0.2.0=pyhcf101f3_2
  - tbb=2022.3.0=hd094cb3_1
  - terminado=0.18.1=pyh5737063_0
  - thinc=8.3.10=py312h9b46583_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_3
  - tomli=2.3.0=pyhcf101f3_0
  - tomlkit=0.13.3=pyha770c72_0
  - tornado=6.5.2=py312he06e257_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - trove-classifiers=2025.11.14.15=pyhd8ed1ab_0
  - typer=0.20.0=pyhefaf540_1
  - typer-slim=0.20.0=pyhcf101f3_1
  - typer-slim-standard=0.20.0=h4daf872_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - ujson=5.11.0=py312ha1a9051_1
  - unicodedata2=17.0.0=py312he06e257_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uritemplate=4.2.0=pyhd8ed1ab_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vega_datasets=0.9.0=pyhd8ed1ab_1
  - vegafusion=1.6.9=pyhd8ed1ab_0
  - vegafusion-python-embed=1.6.9=py312hf664a67_3
  - virtualenv=20.35.4=pyhd8ed1ab_0
  - visions=0.7.1=pyhd8ed1ab_0
  - vl-convert-python=1.8.0=py312h2f7dbde_1
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wasabi=1.1.3=pyhd8ed1ab_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - weasel=0.4.3=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - wrapt=1.17.3=py312he06e257_1
  - xgboost=3.1.1=cpu_pyhb39878e_0
  - xorg-libice=1.1.2=h0e40799_0
  - xorg-libsm=1.2.6=h0e40799_0
  - xorg-libx11=1.8.12=hf48077a_0
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xorg-libxext=1.3.6=h0e40799_0
  - xorg-libxpm=3.5.17=h0e40799_1
  - xorg-libxt=1.3.1=h0e40799_0
  - xyzservices=2025.10.0=pyhd8ed1ab_0
  - yaml=0.2.5=h6a83c73_3
  - yarl=1.22.0=py312h05f76fc_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.5=h32d8bfd_0
  - zstandard=0.25.0=py312he5662c2_1
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - altair-ally==0.1.1
      - emoji==2.15.0
      - imageio==2.37.2
      - mglearn==0.2.0
      - scipy==1.16.3
      - spacymoji==3.1.0
prefix: C:\Users\7luck\Miniforge3\envs\dsci573
