name: 'dsci-573'
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<3.13  # Can be updated next year
  - pip
  - ipykernel
  - nb_conda_kernels
  - otter-grader=6.*  # Can be updated next year
  - altair-all=5.4.*  # Can be updated next year
  - vega_datasets
  - scipy
  - matplotlib>=3.2.2
  - scikit-learn
  - requests>=2.24.0
  - graphviz
  - python-graphviz
  - eli5
  - shap>=0.45  # Breaking changing in model output format https://github.com/shap/shap/issues/3581
  - jinja2
  - lightgbm
  - spacy
  - xgboost
  - catboost
  - nltk
  - imbalanced-learn
  - statsmodels
  - seaborn
  - pip:
    - mglearn
    - spacymoji
    - altair_ally>=0.1.1  # New default plotting behavior
