name: dsci522project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=1.5.*
  - numpy<2.0
  - matplotlib=3.7.*
  - seaborn
  - scikit-learn=1.2.*
  - statsmodels=0.14.*
  - altair
  - altair-all
  - git
  - jupyter
  - jupyterlab
  - jupyterlab-git
  - ipykernel
  - nb_conda_kernels
  - pip
  - polars
  - pytest
  - quarto=1.5.57
  - vl-convert-python=1.1
  - tabulate
  - pip:
      - altair-ally
      - pointblank
      - deepchecks
      - click==8.2.1
      - ucimlrepo==0.0.7