name: dsci522project
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pandas
  - numpy<2.0
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - altair
  - altair-all
  - git
  - jupyter
  - jupyterlab
  - jupyterlab-git
  - ipykernel
  - nb_conda_kernels
  - pip
  - pip:
      - altair-ally
      - pointblank
      - deepchecks

